### ISSUE TITLE
Upper limit on following?

### ISSUE THREAD

**Issue by azizLIGHT** [Lupusanghrenn/MultiTwitchExtension#1]
I added all my followers using my channel name (azizLIGHT) and then noticed not every follow was added, after I did a sort. So I added one more I remember (forsen) and then things started to break. The extension just spins infinitely and doesnt load anything. I removed some followers and tried again, and it worked. So I think there is a limit on how many following I can put into the options. Any ideas? You can try with my channel/follows if you want to confirm

**Comment by Lupusanghrenn** [comment]
the twitch API have a limit of 100 users per request and per response ...
but I can try to send more than one request to exceed this limit 
I will take a look

**Comment by Lupusanghrenn** [comment]
Yup as I tought it was the limit.
That limit work when getting user's follow but also when getting streams !
I'm currently working on it, watch for new commits !

**Comment by Lupusanghrenn** [comment]
Only for the first 100 on the background script (prioritize the favorite channel)

**Comment by azizLIGHT** [comment]
Yes, it seems I can get 100 of my following now successfully. Is there any possibility to get all of them?

**Comment by Lupusanghrenn** [comment]
it should already be that way ! but the extension don t add already added channel

**Comment by azizLIGHT** [comment]
It stops for me at 100. I get some errors like this: 
![image](https://user-images.githubusercontent.com/8013867/59978564-47bb8880-95e6-11e9-8156-48967bdf2eaf.png)
log: https://gist.github.com/azizLIGHT/e64867c1ee9c0b2a8969a7bebe2d6217

I'm not an expert at coding otherwise I could help more 🤔

**Comment by azizLIGHT** [comment]
I uninstalled and reinstalled to remove all data, and retried with my name azizLIGHT and it happens too. Is it something to do with my twitch account then?

**Comment by Lupusanghrenn** [comment]
nop ! this is my bad xD 
I ll fix this asap

**Comment by Lupusanghrenn** [comment]
Done

**Comment by azizLIGHT** [comment]
I'm sorry to bother you again, but it really is not getting more than 100 for me still 😕 This time I see no error in the console either! I did uninstall/reinstall extension and got version 2.2.2. Can you try it with my twitch username 'azizlight' and you can see that it's only getting 100 still, when I have 267 following...

**Comment by Lupusanghrenn** [comment]
wtf I was trying with you re account 
I will look into this

**Comment by Lupusanghrenn** [comment]
I hope it's fixed now
