### ISSUE TITLE
Group by game

### ISSUE THREAD

**Issue by azizLIGHT** [Lupusanghrenn/MultiTwitchExtension#2]
Would be cool if there was an option to group channels by the current game they are playing, and then sort by viewer amount, within the group. Maybe something like these pictures: 
![image](https://user-images.githubusercontent.com/8013867/52433596-6e679f80-2adb-11e9-9050-4537003ad631.png)
![image](https://user-images.githubusercontent.com/8013867/52433672-9951f380-2adb-11e9-80c8-557e619f831d.png)

I think it helps you see what game/event is going on, like if there’s been a new game release that everyone is on, right away, or if there is some kind of tournament going on. As an option, you could enable/disable it if not needed

**Comment by Lupusanghrenn** [comment]
that's a great idea I ll try to do something like the second picture 
and as a option, it will be like 2 different layout : default layout, group by game layout

**Comment by azizLIGHT** [comment]
Thank you! I look forward to seeing the updated extension soon 👍

**Comment by Lupusanghrenn** [comment]
It should be available soon ! 
But I need to run more test for the 1 issues (100 users limit)

**Comment by Lupusanghrenn** [comment]
Available !!
Looking forward to your feebacks

**Comment by azizLIGHT** [comment]
Excellent job!!
