### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by azizLIGHT** [Lupusanghrenn/MultiTwitchExtension#3]
If we can select certain streamers to be special and higher priority on the list, to show above all others, regardless of viewer count, it would be awesome. I follow a lot of streamers and sometimes it is easy to miss certain streamers in the list because of their random view count, so they’re not always at the top or bottom. If they were in their own section/subheading at the very top, it would give them the priority they deserve and be immediately clickable

**Comment by Lupusanghrenn** [comment]
I got the same problem and honestly for the 3 issues you mention,that one is the easiest
I ll make that ASAP

**Comment by azizLIGHT** [comment]
Thanks, this is amazing

**Comment by Lupusanghrenn** [comment]
Nice you like it!
don't forget to ask me for any other improvements
